%YAML 1.2

# camera settings

## int
mode: 3    # 0:none, 1:BGR888, 2: raw, 3: both
bayer_as_rgb: 0

## float
exposure_target_value: 25.0

## in micro seconds, int
exposure_time_min: 100
exposure_time_max: 19000

## in DB, float
exposure_gain_min: 0.0
exposure_gain_max: 15.0

## int
fps: 10

# other settings

ros_topic_color: "/blackfly/cam%/image_color"
ros_topic_raw: "/blackfly/cam%/image_raw"    # raw image is still in BGR888 format but each pixel has only one non-zero channel
additional_topic: "/blackfly/additional"
skip: 1
